# Generated by Django 5.2.5 on 2025-08-07 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('album', models.CharField(blank=True, max_length=255)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('file_size', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('channel', models.CharField(choices=[('music', 'Music'), ('talk', 'Talk'), ('tv', 'TV'), ('ambient', 'Ambient')], max_length=16)),
                ('artwork_path', models.CharField(blank=True, max_length=255)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('last_played_at', models.DateTimeField(blank=True, null=True)),
                ('liked', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sui_track',
            },
        ),
        migrations.CreateModel(
            name='Playback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('source_channel', models.CharField(blank=True, max_length=16)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sui.track')),
            ],
            options={
                'db_table': 'sui_playback',
            },
        ),
    ]
